(ns malli-model.tiny (:require [malli-model.trace :refer [trace-ns]]))
(defn lookup [k R] (or (get R k) (throw (ex-info (str "not in scope: " k) {}))))
(defn check [s f] (f))
(defn validator [s {:keys [R] :as o}]
  (if (contains? R s) (validator (lookup s R) o)
      (case (first s)
        := (let [[_ x] s] #(check s (fn [] (= x %))))
        :seqable (let [[_ c] s, f (validator c o)] #(check s (fn [] (and (seqable? %) (every? f %)))))
        (throw (ex-info (str "invalid schema " (pr-str s)) {})))))
(defn validate [s o v] ((validator s o) v))
(trace-ns)
